URL=http://localhost:8888
DEFAULT_LANGUAGE=en_US

# Nginx
HTTP_IP=localhost
HTTP_PORT_IP=8888

# OIDC
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_AUTH_URI=
OIDC_TOKEN_URI=
OIDC_USERINFO_URI=
OIDC_DISPLAY_NAME=OpenID

# Global
NETWORKS=outlinewiki
NETWORKS_EXTERNAL=false

# MinIO
MINIO_BROWSER=on
MINIO_HTTP_IP=localhost
MINIO_HTTP_PORT=19001
