URL=http://localhost:8888
DEFAULT_LANGUAGE=en_US
TIME_ZONE=UTC
FORCE_HTTPS=false

# Nginx
HTTP_IP=127.0.0.1
HTTP_PORT_IP=8888

# Global
NETWORKS=outlinewiki
NETWORKS_EXTERNAL=false

# MinIO
MINIO_BROWSER=on
MINIO_HTTP_IP=127.0.0.1
MINIO_HTTP_PORT=19001
